### PR TITLE
Revert "Bump actions/setup-python from 4.1.0 to 4.2.0"

### PR DESCRIPTION
**Pull request by SuYe99**
Reverts GERSL/pycold#5

### CODE REVIEW

**Comment by SuYe99** [comment]
@Erotemic Jon, I kept encountering errors for 'lint_job' when merging this branch. Could you help double check it? It seems to be GDAL issue.

**Comment by Erotemic** [comment]
It looks like the error is real. The linter is saying that `gdal` and `gdal_array` are not defined. 

```
./src/python/pycold/imagetool/prepare_ard.py:168:16: F821 undefined name 'gdal'
    driver_t = gdal.GetDriverByName(gdal_driver)  # http://www.gdal.org/formats_list.html
               ^
./src/python/pycold/imagetool/prepare_ard.py:171:12: F821 undefined name 'gdal'
    inDs = gdal.Open(file_name, gdal.GA_ReadOnly)
```


Use the "./run_linter.sh" script locally. It will tell you that you have an undefined variable and any other linting issues. (Note: most editors support adding some form of linting directly in the editing interface, I use the ALE plugin with flake8 for vim to do my linting. VSCode also has some great plugins to get flake8 results directly in the editor).  

Adding from `osgeo import gdal` and `from osgeo import gdal_array` to the top of `prepare_ard.py` fixes the issue. 

EDIT: FWIW, you probably shouldn't revert #5, I don't think it's the cause of any error. It looks like commit eb5ed3c6cfb48edb824f6d9b9106d33eb73b6243 was the source of the issue.

**Comment by SuYe99** [comment]
can't believe that these imports were removed by accident.
I also added import fiona package in prepare_ard.py. I found that fiona was missing in the requirement. But the CI on my recent push is still successful. It is weird. Did I miss something?

Su

**Comment by Erotemic** [comment]
> can't believe that these imports were removed by accident.

This is likely because you merged devel into your branch before merging it back into devel. I've always had issues doing it that way (although I do believe it is a valid way to do it, but I don't have enough experience with it to know what the pitfalls are). What I usually do when I have a branch that is outdated from whatever the "main" branch is (in this case 'devel'), is I rebase my changes on top of that branch. 

I wrote a small doc with references on how to do this in the WATCH repo: https://gitlab.kitware.com/smart/watch/-/blob/main/docs/rebasing_procedure.md

> I also added import fiona package in prepare_ard.py. I found that fiona was missing in the requirement. But the CI on my recent push is still successful. It is weird. Did I miss something?

Yes, fiona also got incorrectly removed. I missed that when I made my first comment. I don't see any new changes on the CI. Where is your recent push?

**Comment by SuYe99** [comment]
> This is likely because you merged devel into your branch before merging it back into devel. I've always had issues doing it that way (although I do believe it is a valid way to do it, but I don't have enough experience with it to know what the pitfalls are). What I usually do when I have a branch that is outdated from whatever the "main" branch is (in this case 'devel'), is I rebase my changes on top of that branch.

That was exactly what I was doing. It is good to know that rebasing the change could resolve the issue.  I will follow your routine for future. 

> Yes, fiona also got incorrectly removed. I missed that when I made my first comment. I don't see any new changes on the CI. Where is your recent push?

I directly pushed it to the devel repo, just for convenience. I will create a new branch for future.

**Comment by Erotemic** [comment]
> I directly pushed it to the devel repo, just for convenience. I will create a new branch for future. 

I do that all the time (usually hotfixes). It's NBD, but feature branches do help to ensure nothing breaks :)

If you're interested, we can also turn on cibuildwheel for other Python versions and get a Github Action step in there to publish pycold to PYPI whenever a new tag is created (e.g. via the Github Release Interface). It would make watch integration a lot nicer if we can pip install a specific known working version of pycold. 

It looks like nobody has taken the name yet: https://pypi.org/project/pycold/  I would register a PYPI account and claim that name. Not sure if you can claim a name from the web interface.You might need to upload a package.

It wouldn't be too hard to manually upload one of the wheels the CI built: https://github.com/GERSL/pycold/suites/8158007680/artifacts/354178612

You can do that via `twine` (`pip install twine`): and then run:

```bash
# For testing: TWINE_REPOSITORY_URL=https://test.pypi.org/legacy
TWINE_REPOSITORY_URL=https://upload.pypi.org/legacy/
twine upload --username "$TWINE_USERNAME" --password=$TWINE_PASSWORD \
                --repository-url "$TWINE_REPOSITORY_URL" \
                "$WHEEL_PATH" --skip-existing --verbose || { echo 'failed to twine upload' ; exit 1; }
```

If you want to do auto publishing you will need to create a github secret with a pypi token for your account as well. If you tell me what the environment variable is named I'll add the action to publish to pypi whenever a new tag is made.

**Comment by SuYe99** [comment]
I like the idea of 'tagging' a certain version of pycold, so that my continued development won't break your system, though I never published package in PYPI before. I am studying from the PYPI website right now; it will take a while. But sure, I certainly hope that pycold could be released through pypi. If my understanding is correct, if we put PYCOLD in pypi, the users could directly install it through 'pip install'? (even for window users?)

**Comment by Erotemic** [comment]
Yes, uploading to pypi will allow people to pip install it. However, there are caveats because this package has a binary distribution: the CI needs to build a _wheel_ for each platform / operating system. 

It is possible to release a source tarball on pypi, which means _if_ the user has all of the binary dependencies and a compiler, pip install will built it for them, but that is often very difficult to work with (that's why we don't pip install gdal here, and instead we use wheel published on Kitware's girder server). So often source and binary distributions are released together. For example, see the packages I released for [networkx_algo_common_subtree](https://pypi.org/project/networkx-algo-common-subtree/#files). You will see there is a wheel for different operating systems (windows, osx, linux), python versions: cp37, cp38, etc..., and currently only one architecture (x86_64 i.e. 64 bit x86 or amd64 processors, but other architectures like arm64 (i.e. rasberry pi CPUs) or i686 (32 bit CPUs) could be supported, but they would have a specific machine build those wheels.

With this repo, I want to mainly target manylinux wheels, because that's a lot easier to work with, but we can try to build windows wheels as well. That is possible on Github Actions CI.

For PYPI, all you need to do is create an account. Then go to account settings: 

image

Scroll down to the API tokens section and click Add API token: 

image. 

Copy down this token and store it somewhere safe. If you lose it you will have to revoke it and make a new one.

Then go to github on this project and click the "..." option for the repo and go to Settings. Then under security click "Secrets" and then "Actions". 

image

Click the button New Repository Secret: and set the "Name" to the name of the token, and then set the "Secret" to the secret value that you copied down. And finally hit "Add Secret". 

Once you've done this, tell me the name of your secret, and I will setup the github action to publish to pypi. 

You should also do this on the https://test.pypi.org/ site, which is a completely distinct site from pypi.org, but is used to test that your uploads are good. So make an account there, another secret token (with a different name, i.e. prefixed with `TEST_` and then do the same process to add that as a second repo secret. That will allow PRs to test that they can publish to test.pypi, but when you make a tag it will publish to real pypi.

**Comment by SuYe99** [comment]
@Erotemic thank you for such detailed instruction. Yes, I already added 'PYPI' (for pypi) and 'PYPI_TEST' (for test.pypi) in repo secrets. Let me know if it works.

**Pull request closed without merging**
