### PR TITLE
Linting / Tweaks / Fixes / CI / Docker

### PR DESCRIPTION
**Pull request by Erotemic**
This builds on my previous patch #3

I ran a linter on the code: 

```python
flake8 --max-line-length 79 '--ignore=B006,B007,B009,C401,C405,C408,C409,C414,C416,E123,E126,E127,E201,E202,E203,E221,E222,E241,E26 ,E265,E266,E271,E272,E301,E305,E306,E501,EXE001,EXE002,I100,I201,N801,N802,N803,N804,N805,N806,N807,N811,N812,N813,N814,N817,N818,W503,W504,W602' --statistics src/python/pycold
```

Which uses the same linting style that WATCH uses. I fixed the errors, which exposed that there were several unused / undefined variables that would have raised errors.

Additionally in terms of style it made spacing and indentation consistent across all files. I.e. 2 lines between top-level functions, whitespace around operators, removing over-indented lines. 

I also separated out the ignore warnings into a separate module called "monkey" for [monkey patching](https://en.wikipedia.org/wiki/Monkey_patch). This separates the "dirty" import time effects into a single file, which can aid in debugging. 

There were also several `import gdal` statements that needed to become `from osgeo import gdal`, which I fixed. 

I'm now able to run the tests on my machine, although I do get two errors: 

```
FAILED tests/test_sccd.py::test_sccd_detect - assert array([134], dtype=int32) == 141
FAILED tests/test_sccd.py::test_sccd_update - ValueError: Expected a dimension of size 5, got 4
```

Perhaps the test needs to be updated?

### CODE REVIEW

**Comment by Erotemic** [comment]
This PR now includes improvements to run_developer_setup.py that ensure the appropriate requirements are installed. Additionally I added dockerfiles where I've verified that the build works correctly in a clean environment. @SuYe99

**Comment by Erotemic** [comment]
I've also included ./build_whee.sh script which uses cibuildwheel to build manylinux wheels for this package. Additionally I added a github actions CI that runs this and produces wheels as an artifact. This means that binary wheels are now produced as a CI artifact, and thus can be uploaded to pypi, which would make pycold pip installable.

I can help with getting the CI to automatically push those wheels to pypi as well, but I want to ensure we have all the tests passing first (as well as ensuring there are robust enough tests that put this through the paces we will need for the watch system).

After this branch is merged, this repo will start running CI on github actions. For a preview of what that looks like, the CI is running on my fork: https://github.com/Erotemic/pycold/actions

**Comment by Erotemic** [comment]
I've been looking into why the sccd test are failing. It seems like the pickled data in `tests/resources/spectral_15043028_sccdplot.pickle` does not have the same `nrtmodel_dt` data type as the library currently defines. 

I think we merge this branch and then look into those test errors more closely.

**Comment by SuYe99** [comment]
Hi Jon, I haven't updated the S-CCD testing functions (it is still in active development), which was causing testing fail.
We can either 1) let me update S-CCD testing function; or 2) let's remove S-CCD from CI test (so far I don't need CI for S-CCD) until a stable version of S-CCD is finished. Which way do you prefer? Let me know it, and I can update it right away.

**Comment by Erotemic** [comment]
Given that it's still in development I'll add a `pytest.skip()` to those functions and reenabled the tests for the wheels. This changes includes a "run_tests.py" script that generates test coverage for the project, and to get that to work I had to also make some changes to the tests themselves to use pathlib and `__file__` to locate the resources instead of relying on being in a specific directory.

That should result in a green dashboard on my fork. After that is green this PR should be merged.

Then as you continue to develop SCCD you can remove those skips to enable that test and ensure it passes before merging in the updates.

**Comment by Erotemic** [comment]
The dashboard is green: https://github.com/Erotemic/pycold/actions/runs/2995095644

This is ready to be merged.

**Pull request merged**
